version: "3.9"
services:
  server:
    build: ./
    container_name: cloudservice-server
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db

    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "demo"
      POSTGRES_PASSWORD: "demo"
    ports:
      - "5432:5432"